
pub const WORDS: [(u64, &'static str); 104] = [
  (1,"A sweatshirt"),
  (2,"Somersault"),
  (3,"Messy hair"),
  (4,"Belly laugh"),
  (5,"Jumping rope"),
  (6,"Shoelaces tied together"),
  (7,"Different point of view"),
  (8,"Clouds that look like something else"),
  (9,"Happy reunion"),
  (10,"Bald spot"),
  (11,"Disappointment"),
  (12,"Siblings"),
  (13,"Behind the scenes"),
  (14,"Stain"),
  (15,"Wonderful surprise"),
  (16,"Chapped lips"),
  (17,"Incognito"),
  (18,"Chain-link fence"),
  (19,"Cat sleeping in a window"),
  (20,"Afternoon light"),
  (21,"Christmas lights"),
  (22,"Reflection"),
  (23,"Book covers"),
  (24,"Hanging laundry"),
  (25,"Strangers"),
  (26,"Black and white"),
  (27,"Pierced ears"),
  (28,"Thumb wrestlling"),
  (29,"Arrow pointing up"),
  (30,"Soft"),
  (31,"Green"),
  (32,"Splash"),
  (33,"Blur"),
  (34,"Wrinkles"),
  (35,"View from above"),
  (36,"Something hidden"),
  (37,"Half full"),
  (38,"What's in your pocket"),
  (39,"Peeking"),
  (40,"Empty table"),
  (41,"Your next door neighbor"),
  (42,"Inside your fridge"),
  (43,"Night in the city"),
  (44,"Drawing of a photograph"),
  (45,"Collection"),
  (46,"Dancing"),
  (47,"Hunted house"),
  (48,"Security guard"),
  (49,"Funny shape"),
  (50,"Smiling baby"),
  (51,"Accident waiting to happen"),
  (52,"Nerds"),
  (53,"Closed sign"),
  (54,"Vacant lot"),
  (55,"Optical illusion"),
  (56,"Thinking"),
  (57,"Neon sign"),
  (58,"Today's date"),
  (59,"Celebration"),
  (60,"Your parents"),
  (61,"Under the cover"),
  (62,"Barking dog"),
  (63,"In a hurry"),
  (64,"Graffiti"),
  (65,"Wild animal"),
  (66,"Downtown"),
  (67,"Spiderweb"),
  (68,"Broken glass"),
  (69,"Make up"),
  (70,"Running water"),
  (71,"Deserted street"),
  (72,"Family heirloom"),
  (73,"Rocks"),
  (74,"Unmade bed"),
  (75,"From big to little"),
  (76,"Winding staircase"),
  (77,"High five"),
  (78,"Long time"),
  (79,"Melting ice cream"),
  (80,"Sparks"),
  (81,"Messy wires"),
  (82,"Hole in the ground"),
  (83,"Power lines"),
  (84,"Flock of bird"),
  (85,"Graveyard"),
  (86,"Sunny side up"),
  (87,"The tallest building"),
  (88,"Movie marquee"),
  (89,"Butterfly kiss"),
  (90,"List"),
  (91,"Hand shadows"),
  (92,"Fighter"),
  (93,"Stripes"),
  (94,"Bridge"),
  (95,"Fashion"),
  (96,"Yellow traffic light"),
  (97,"Silence"),
  (98,"Hard work"),
  (99,"Rip"),
  (100,"Cosy"),
  (101,"Fork in the road"),
  (102,"Winner"),
  (103,"Homemade"),
  (104,"Hiding place"),
];
