
pub const WORDS: [(u64, &'static str); 104] = [
  (1,"Un sweat-shirt"),
  (2,"Un saut périlleux"),
  (3,"Des cheveux en bataille"),
  (4,"Un fou rire"),
  (5,"Une corde à sauter"),
  (6,"Des lacets attachés"),
  (7,"Différents points de vue"),
  (8,"Des nuages qui ressemblent à autre chose"),
  (9,"De joyeuses retrouvailles"),
  (10,"Calvitie"),
  (11,"Une déception"),
  (12,"Des frères et soeurs"),
  (13,"En arrière scène"),
  (14,"Une tache"),
  (15,"Une merveilleuse surprise"),
  (16,"Des lèvres gercées"),
  (17,"Incognito"),
  (18,"Un grillage"),
  (19,"Un chat qui dors à la fenêtre"),
  (20,"Les lumières de l'après-midi"),
  (21,"Des décorations de noël"),
  (22,"Une réflection"),
  (23,"Des couvertures de livre"),
  (24,"Du linge qui sèche"),
  (25,"Des étrangers"),
  (26,"Noir & blanc"),
  (27,"Des oreilles perçées"),
  (28,"Une battaile de pouces"),
  (29,"Une flèche qui pointe vers le haut"),
  (30,"Doux"),
  (31,"Vert"),
  (32,"Une éclaboussure"),
  (33,"Flou"),
  (34,"Ridé"),
  (35,"Vu du dessus"),
  (36,"Quelque chose de caché"),
  (37,"À demi plein"),
  (38,"Ce qu'il y a dans ta poche"),
  (39,"Coup d'oeil furtif"),
  (40,"Une table vide"),
  (41,"Votre voisin"),
  (42,"À l'intérieur de votre frigo"),
  (43,"Une soirée en ville"),
  (44,"Le dessin d'un photographie"),
  (45,"Une collection"),
  (46,"Dance"),
  (47,"Une maison hantée"),
  (48,"Un agent de sécurité"),
  (49,"Une forme amusante"),
  (50,"Un bébé qui sourit"),
  (51,"Un accident voué à se produire"),
  (52,"Nerds"),
  (53,"Un panneau \"fermé\""),
  (54,"Un terrain vacant"),
  (55,"Une illusion d'optique"),
  (56,"Penser"),
  (57,"Un enseigne néon"),
  (58,"La date d'aujourd'hui"),
  (59,"Une fête"),
  (60,"Vos parents"),
  (61,"Sous les couvertures"),
  (62,"Un chien qui abboie"),
  (63,"Pressé"),
  (64,"Un graffiti"),
  (65,"Un animal sauvage"),
  (66,"centre-ville"),
  (67,"Une toile d'araignée"),
  (68,"Du verre brisé"),
  (69,"Du maquillage"),
  (70,"De l'eau qui court"),
  (71,"Une rue déserte"),
  (72,"Un héritage de famille"),
  (73,"Des pierres"),
  (74,"Un lit défait"),
  (75,"De gros à petit"),
  (76,"Un escalier en colimason"),
  (77,"\"High five\""),
  (78,"Longtemps"),
  (79,"De la glace qui fond"),
  (80,"Des étincelles"),
  (81,"Des cables en désordre"),
  (82,"Un trou dans le sol"),
  (83,"Des lignes électriques"),
  (84,"Un vol d'oiseaux"),
  (85,"Un cimetierre"),
  (86,"\"Sunny side up\""),
  (87,"Le plus haut batiment"),
  (88,"Une affiche de cinéma"),
  (89,"Un baiser"),
  (90,"Une liste"),
  (91,"Des ombres chinoises"),
  (92,"Combattant"),
  (93,"Des bandes"),
  (94,"Un pont"),
  (95,"La mode"),
  (96,"Un feu à l'orange"),
  (97,"Silence"),
  (98,"Un dur travail"),
  (99,"Une déchirure"),
  (100,"Confortable"),
  (101,"Une patte d'oie"),
  (102,"Gagnant"),
  (103,"Fait-maison"),
  (104,"Une cachette"),
];
